services:
  influx:
   image: influxdb:2.0
   env_file:
    - ./.env
   volumes:
    - influxdb:/var/lib/influxdb2
   ports:
    - 8086:8086
  monitor:
    build: ./
    depends_on:
      - influx

volumes:
 influxdb: {}